"""
Astrology calculations and message generation for the Telegram bot.

This module provides a lightweight, offline implementation of astrological
transit analysis. For the sake of demonstration and reliability in
environments without internet access, the positions of the planets are
approximated using simple orbital period ratios rather than high precision
JPL ephemerides. Although the resulting transits are not suitable for
serious astrological work, they still allow us to generate varied and
entertaining horoscope messages.

Key functions:

* ``compute_natal_positions`` – compute approximate natal positions of
  selected planets based on the user's birth date.
* ``compute_transit_differences`` – compute the current angular distance
  between the natal positions and today's positions for each planet.
* ``generate_message`` – build a motivational daily message from the
  computed transits, incorporating humour, spiritual guidance and
  inspirational quotes.

If you wish to use real planetary positions with high accuracy, replace
the simplified computations here with calls to the Skyfield library.
"""

from __future__ import annotations

import random
from datetime import date, datetime, timedelta
from typing import Dict, Tuple

import pytz

# Orbital periods in days for selected celestial bodies.  
# These values are approximate but sufficient for our purposes.
PLANET_PERIODS = {
    "Sun": 365.25,
    "Moon": 27.32,
    "Mercury": 88.0,
    "Venus": 224.7,
    "Mars": 687.0,
    "Jupiter": 4332.59,
    "Saturn": 10759.22,
}

# Lists of themes and suggestions for daily messages.  
# Feel free to expand these lists with additional items to enrich the
# variety of messages generated by the bot.
THEMES = [
    "Гармония и принятие",
    "Внутренняя сила",
    "Творчество и вдохновение",
    "Баланс и созерцание",
    "Свобода и ответственность",
    "Любовь и благодарность",
    "Уверенность и рост",
]

ACTION_SUGGESTIONS = [
    "Обрати внимание на свои желания.",
    "Проведи время наедине с собой.",
    "Сделай то, что давно откладывал(а).",
    "Поделись теплом с близкими.",
    "Запиши свои цели и представь, что они уже осуществились.",
    "Сделай небольшой шаг к мечте.",
]

WARNING_SUGGESTIONS = [
    "Не игнорируй тревогу.",
    "Не позволяй сомнениям управлять тобой.",
    "Не забывай отдыхать.",
    "Не недооценивай свои силы.",
    "Не затягивай с важными разговорами.",
]

RITUALS = [
    "Посмотри на небо и вспомни три своих мечты.",
    "Напиши благодарность за пять вещей в твоей жизни.",
    "Сделай несколько глубоких вдохов и улыбнись.",
    "Послушай любимую музыку и потанцуй.",
    "Запиши свои чувства в дневник.",
]

MANTRAS = [
    "Осознанность создаёт свободу.",
    "Я заслуживаю всего лучшего.",
    "Мир отражает моё внутреннее состояние.",
    "Любовь – это моя сила.",
    "Сегодня я принимаю себя полностью.",
]

# Quotes from the film "The Secret" (Rhonda Byrne) and the book "Happy Pocket Full of Money".  
# These inspirational excerpts are used to conclude each daily message.
QUOTES_SECRET = [
    "Мы можем создать любую реальность, если только поверим в неё.",
    "Когда вы хотите что‑то, вся Вселенная будет способствовать тому, чтобы вы это получили.",
    "Мы становимся тем, о чём думаем.",
    "Каждая мысль – это энергия. И когда вы думаете, вы излучаете энергию.",
]

QUOTES_MONEY = [
    "Деньги – это просто форма энергии, которая любит тех, кто любит её.",
    "Благодарность умножает ваши богатства.",
    "Ваше богатство – это состояние вашего ума.",
    "Обилие приходит к тем, кто излучает радость.",
]


def _days_since_epoch(d: date) -> int:
    """Return number of days since a fixed epoch (1 Jan 2000).

    We choose 2000‑01‑01 as a convenient epoch for calculations. The
    absolute choice is arbitrary since we only care about differences
    between dates.
    """
    epoch = date(2000, 1, 1)
    return (d - epoch).days


def _approximate_position(days: int, period: float) -> float:
    """Compute an approximate ecliptic longitude (in degrees) for a body.

    :param days: Number of days since epoch
    :param period: Orbital period in days
    :return: Angle in degrees on the [0, 360) interval
    """
    # Simple linear progression around the circle
    fraction = (days % period) / period
    return (fraction * 360.0) % 360.0


def compute_natal_positions(birth_date: str, birth_time: str) -> Dict[str, float]:
    """Compute approximate natal positions for selected planets.

    :param birth_date: Birth date in ISO format (YYYY‑MM‑DD)
    :param birth_time: Birth time in HH:MM format (24h)
    :return: Mapping from planet name to ecliptic longitude in degrees
    """
    dt = datetime.strptime(birth_date + " " + birth_time, "%Y-%m-%d %H:%M")
    d = dt.date()
    days = _days_since_epoch(d)
    positions: Dict[str, float] = {}
    for planet, period in PLANET_PERIODS.items():
        positions[planet] = _approximate_position(days, period)
    return positions


def compute_transit_differences(natal_positions: Dict[str, float], current_date: date) -> Dict[str, float]:
    """Compute angular differences between natal and current positions.

    :param natal_positions: Result of ``compute_natal_positions``
    :param current_date: Date for which to compute transits
    :return: Mapping from planet name to absolute angular distance in degrees
    """
    days_now = _days_since_epoch(current_date)
    differences: Dict[str, float] = {}
    for planet, natal_pos in natal_positions.items():
        period = PLANET_PERIODS[planet]
        current_pos = _approximate_position(days_now, period)
        diff = abs(current_pos - natal_pos)
        # Ensure difference is within [0, 180]
        if diff > 180.0:
            diff = 360.0 - diff
        differences[planet] = diff
    return differences


def _interpret_transit(diff: float) -> str:
    """Return a simple interpretation based on angular difference.

    Conjunctions (<10°), oppositions (~180°) and trines (~120°) produce
    different types of energies. These interpretations are deliberately
    simplified for demonstration purposes.
    """
    if diff < 10.0:
        return "конъюнкция"
    elif 170.0 <= diff <= 190.0:
        return "оппозиция"
    elif 110.0 <= diff <= 130.0:
        return "трин"
    elif 80.0 <= diff <= 100.0:
        return "квадрат"
    else:
        return "аспект"


def generate_message(name: str, natal_positions: Dict[str, float]) -> str:
    """Generate a daily horoscope message for the user.

    The message is built from several parts: a greeting, a theme of the day,
    interpretations of the most significant transit, suggestions for action
    and caution, a simple ritual, a mantra and a quote for reflection.

    :param name: User's first name for personalisation
    :param natal_positions: Natal planetary positions for the user
    :return: A formatted string ready to send via Telegram
    """
    today = date.today()
    diffs = compute_transit_differences(natal_positions, today)
    # Identify the planet with the smallest angular distance (strongest transit)
    planet, angle = min(diffs.items(), key=lambda item: item[1])
    interpretation = _interpret_transit(angle)
    # Construct the narrative pieces
    theme = random.choice(THEMES)
    actions = random.sample(ACTION_SUGGESTIONS, k=2)
    warnings = random.sample(WARNING_SUGGESTIONS, k=2)
    ritual = random.choice(RITUALS)
    mantra = random.choice(MANTRAS)
    quote = random.choice(QUOTES_SECRET + QUOTES_MONEY)
    # Compose the message in Russian similar to the provided example
    message_lines = [
        f"Доброе утро, {name}!",  # greeting
        "",
        f"🧿 Тема дня: «{theme}». Прислушайся к себе.",
        "",
        f"🌙 Сегодня {planet} образует {interpretation} с твоей натальной картой.",
        "Она приносит особую энергию – постарайся почувствовать её.",
        "",
        "✅ Действуй:",
    ]
    for act in actions:
        message_lines.append(f"• {act}")
    message_lines.append("")
    message_lines.append("❌ Категорически:")
    for warn in warnings:
        message_lines.append(f"• {warn}")
    message_lines.append("")
    message_lines.append("🕯️ Утренний ритуал (5 минут):")
    message_lines.append(ritual)
    message_lines.append("")
    message_lines.append("💬 Девиз дня:")
    message_lines.append(mantra)
    message_lines.append("")
    message_lines.append("✨ Цитата для размышления:")
    message_lines.append(quote)
    return "\n".join(message_lines)
